[package]
name = "quick_link"
version = "0.1.0"
edition = "2021"
authors = [ "Michael Flaherty <michaelwflaherty@me.com>" ]
license = "AGPL-3.0"


[dependencies]
rocket = "0.5.0-rc.2"
lru-cache = "0.1"
rand = "0.8.5"